### ISSUE TITLE
permissão de administrador concedidas

### ISSUE THREAD

**Issue by Lucaskim8** [vandemberg/sre-c2s-challenge#6]
@vandemberg @fellipe30k  concedi permissões de adeministrador para vocês e estou caminhando o link do meu projeto : https://github.com/Lucaskim8/sre-c2s-challenge

**Comment by fellipe30k** [comment]
@Lucaskim8 você não criou o PR com o relatório dos bugs encontrados 
![image](https://github.com/vandemberg/sre-c2s-challenge/assets/32600288/7f2f63de-6cfe-4684-92f8-ccbfc31a345a)

**Comment by Lucaskim8** [comment]
@vandemberg @fellipe30k  https://github.com/vandemberg/sre-c2s-challenge/pull/5 estou mandando o link que cai na minha pull request com o relatório completo, devo ter feito alguma confusão.
